CREATE TABLE CATEGORY (
    ID int(9) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);
CREATE TABLE PRODUCT (
    ID int(9) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CATEGORY int(9) NOT NULL
);
